language: rust
sudo: required
addons:
  apt:
    packages:
      - libssl-dev

cache: cargo

branches:
  only:
    - master
    - /^test-.*$/

matrix:
  include:
    - rust: stable
      os: linux
      env: RUST_BACKTRACE=1
      before_cache: |
        if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
          cargo install cargo-tarpaulin -f
        fi
      before_script:
        - rustup component add clippy
      script:
        - cargo clean
        - cargo clippy -- -D warnings
        - cargo build --verbose --all
        - cargo clippy --all-targets --all-features -- -D warnings -A clippy::cognitive_complexity
        - cargo test --verbose --all
        - cd wasm && cargo clippy -- -D warnings -A clippy::suspicious_else_formatting
        - cd ../nodejs/native && cargo clippy -- -D warnings
        - cd ../../
      after_success: |
        cargo tarpaulin --exclude-files nodejs wasm parser/mod.rs --out Xml
        bash <(curl -s https://codecov.io/bash)
    - rust: stable
      os: osx
      env: RUST_BACKTRACE=1
      script:
        - cargo clean
        - cargo build --verbose --all
        - cargo test --verbose --all
    - language: node_js
      os: linux
      node_js:
        - '11'
        - '10'
        - '9'
        - '8'
      before_install:
        - curl https://sh.rustup.rs -sSf > /tmp/rustup.sh
        - sh /tmp/rustup.sh -y
        - export PATH="$HOME/.cargo/bin:$PATH"
        - source "$HOME/.cargo/env"
        - npm install -g neon-cli
        - cd nodejs
        - node -v
        - npm -v
        - npm install
      script:
        - npm test
    - language: node_js
      os: osx
      node_js:
        - '11'
        - '10'
        - '9'
        - '8'
      before_install:
        - curl https://sh.rustup.rs -sSf > /tmp/rustup.sh
        - sh /tmp/rustup.sh -y
        - export PATH="$HOME/.cargo/bin:$PATH"
        - source "$HOME/.cargo/env"
        - npm install -g neon-cli
        - cd nodejs
        - node -v
        - npm -v
        - npm install
      script:
        - npm test
    - language: node_js
      os: linux
      node_js:
        - '11'
        - '10'
        - '9'
        - '8'
      before_install:
        - curl https://sh.rustup.rs -sSf > /tmp/rustup.sh
        - sh /tmp/rustup.sh -y
        - export PATH="$HOME/.cargo/bin:$PATH"
        - source "$HOME/.cargo/env"
        - node -v
        - npm -v
      before_script:
        - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
      script:
        - bash ./build-wasm.sh
    - language: node_js
      os: osx
      node_js:
        - '11'
        - '10'
        - '9'
        - '8'
      before_install:
        - curl https://sh.rustup.rs -sSf > /tmp/rustup.sh
        - sh /tmp/rustup.sh -y
        - export PATH="$HOME/.cargo/bin:$PATH"
        - source "$HOME/.cargo/env"
        - node -v
        - npm -v
      before_script:
        - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
      script:
        - bash ./build-wasm.sh